name: Create Version
on:
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Release
        id: step1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
